### ISSUE TITLE
Blank rows during move

### ISSUE THREAD

**Issue by peterpanduro** [FlorianMielke/FMMoveTableView#24]
When I move the first row, everything works as expected. However, the next time I move a row it is completely white. In xcode I am getting the debug message:
"Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates."

I am kind of fixing this by calling reloadData with a slight delay in moveTableView:moveRowFromIndexPath:toIndexPath:

However, if I lift a row and drop it in the same spot, the method above isn't called and the next time I lift a row, it is blank again.

**Comment by aanchalkalani** [comment]
Hi, 

I am also facing the same issue, Please find the screenshot of it. 

Xcode :- 6.1.1
iOS :- 8.1

![ios simulator screen shot 05-jan-2015 6 05 07 pm](https://cloud.githubusercontent.com/assets/6301399/5613185/48c97ede-9506-11e4-8823-068f468419a7.png)


Please do need full.

**Comment by ArtsiomHainetdzinau** [comment]
Got the same issue. Use this code to create snapshot for iOS8:

**Comment by boazin** [comment]
I'm getting it too. However, my cell is complex and I see the default xib (with the default values) and not the rendered cell. It might help explain. (I do see the warning described at the original issue)
