### ISSUE TITLE
How to handle canEditRowAtIndexPath and editActionsForRowAtIndexPath

### ISSUE THREAD

**Issue by aanchalkalani** [FlorianMielke/FMMoveTableView#32]
Hi,
I am trying to make the row editable but its not working. 

Please help.

Thanks,

**Comment by FlorianMielke** [comment]
Can you please provide any sample source and error descriptions/behaviors.

**Comment by aanchalkalani** [comment]
Hi,

As i did canEditRowAtIndexPath return true. 
No error are coming but cell is not becoming editable, no delete option is coming. 

Thanks

**Comment by aanchalkalani** [comment]
Hi,

As i did canEditRowAtIndexPath return true.
No error are coming but cell is not becoming editable, no delete option is
coming.

Could you please guide me, how to do that in the FMTableViewCell/Table,  if
any change is required that classes .


Thanks

On Sat, Jun 13, 2015 at 8:32 PM, Florian Mielke <notifications@github.com>
wrote:

> Can you please provide any sample source and error descriptions/behaviors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FlorianMielke/FMMoveTableView/issues/32#issuecomment-111717527>
> .
>



-- 


*No A@nchal*
*No Life*
*Know A@nchal*
*Know Life *
